version: "3"

services :
    app:
        build: .
        image: appvuejs
        restart: always
        ports: 
            - 8080:8080
        volumes: 
            - ./:/app  
   
     
        
