version: "3.8"

services:
  app:
    build: .
    image: ms-customfields/params
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
    links:
      - redis
    environment:
      CACHE_DRIVER: redis
      REDIS_CLIENT: predis
      REDIS_HOST: redis-ms-customfields/params
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    volumes:
